environment:
    matrix:
    # node.js
    - nodejs_version: "8"

# Install scripts
install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

test_script:
    - node -v
    - npm -v
    - npm test

# Don't automatically build
build: off
